<a href="https://colab.research.google.com/github/Harlequelrah/Learning_data_science/blob/main/Introduction_%C3%A0_la_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy veut dire Numerical Python qui est une bibliothèque pour effectuer des calculs scientifiques avec python.

Quelques liens :
- [Cours Openclassroom](https://openclassrooms.com/fr/courses/7771531-decouvrez-les-librairies-python-pour-la-data-science)
-[Documentation](https://numpy.org/doc/stable/user/index.html)

In [42]:
import numpy as np

Découverte de quelques fonctions avec NumPy

In [68]:
revenus = [1800,1500,2200,3000,2172]
print(f"La moyenne des revenus est {np.mean(revenus)}")

'La moyenne des revenus est 2134.4'

In [73]:
x= [-2,-1,1,2]
print(f"En valeur absolue on a : {np.abs(x)}")
print(f"En exponentielle on a : {np.exp(x)}")
print(f"En logarithme on a : {np.log(np.abs(x))}")

En valeur absolue on a : [2 1 1 2]


'En exponentielle on a : [0.13533528 0.36787944 2.71828183 7.3890561 ]'

'En logarithme on a : [0.69314718 0.         0.         0.69314718]'

Difference entre les arrays et les listes classiques :
- les arrays prennent un seul type de donnée
- les arrays permettent d'effectuer plus simplement et rapidement des opérations complexe
- les arrays facilitent le stockage et la manipulation de données

Créer un array NumPy .
Si dans la liste de départ il y a des données de types différents, NumPy essaiera de tous les convertir au type le plus général.
ex : cas de tableau int et float donnera tableau de float

In [45]:
revenus_array=np.array(revenus)
revenus_array

array([1800, 1500, 2200, 3000, 2172])

In [46]:
print(np.zeros(5))         #array de 0 , de 5 éléménts
print(np.ones(5))          #array de 1 , de 5 éléments
print(np.arange(1,10,1))   #array de 1 à 9 avec pas de 1
print(np.linspace(1,10,4)) #array de 4 éléments espacés uniformement entre 1 et 10

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3 4 5 6 7 8 9]
[ 1.  4.  7. 10.]


In [47]:
revenus_array.dtype # accès au type d'un array

dtype('int64')

In [48]:
t1 = np.array([1,2,3],dtype='f') # creation d'un tableau de float32
t2 = np.array([1,2,3],dtype='d') # creation d'un tableau de float64
print(f"{t1=}")
print(f"{t2=} , {t2.dtype=}")
print(t1.astype(np.int32)) # modification d'un type

t1=array([1., 2., 3.], dtype=float32)
t2=array([1., 2., 3.]) , t2.dtype=dtype('float64')
[1 2 3]


Sélectionner les éléments d'un array

In [49]:
print(revenus_array)
x4=revenus_array[4]  #accès à l'élément 4
x1=revenus_array[1]  #accès à l'élément 1

revenus_array[1]=1900 #modification d'un élément
revenus_array
print(f"{x4=}")
print(f"{x1=}")
print(f"{x4,revenus_array=}")

print(revenus_array[0:3])
print(revenus_array[0:3:2]) # accéder aux éléments de l'index 0 à 3 avec pas de 2
print(revenus_array[:2])
print(revenus_array[2:])
print(revenus_array[::2]) # accéder à un élement sur deux
print(revenus_array[::-1]) #inverser un tableau


[1800 1500 2200 3000 2172]
x4=np.int64(2172)
x1=np.int64(1500)
x4,revenus_array=(np.int64(2172), array([1800, 1900, 2200, 3000, 2172]))
[1800 1900 2200]
[1800 2200]
[1800 1900]
[2200 3000 2172]
[1800 2200 2172]
[2172 3000 2200 1900 1800]


Accéder aux éléments en fonction de conditions

In [50]:
revenus_array[revenus_array>2000] # retourne un array d'éléments superieur à 2000

array([2200, 3000, 2172])

In [51]:
revenus_array[(revenus_array>2000) & (revenus_array<2500)]  # exemple de contidition avec & qui représente and

array([2200, 2172])

In [52]:
revenus_array[(revenus_array%30==0) | (revenus_array%11==0)] # exemple de condition avec | qui représente or

array([1800, 2200, 3000])

In [56]:
revenus_array[revenus_array>2000]=0 #modification de tous les éléments respectant la condition à 0
revenus_array

array([1800, 1900,    0,    0,    0])

Utilisation des méthodes d'array

In [65]:
notes=np.array([17,18,11,14])
print("Le nombre de notes est ",notes.shape)
print("La moyenne des notes est ",np.mean(notes))
print(f"Le minimum des notes est ,{np.min(notes)} et son indice est {np.argmin(notes)}")
print(f"Le minimum des notes est ,{np.max(notes)} et son indice est {np.argmax(notes)}")
print("Le maximum des notes est ",np.max(notes))
print("Le somme des notes est ",np.sum(notes))
print(f"Les notes rangées : ",np.sort(notes))



Le nombre de notes est  (4,)
La moyenne des notes est  15.0
Le minimum des notes est ,11 et son indice est 2
Le minimum des notes est ,18 et son indice est 1
Le maximum des notes est  18
Le somme des notes est  60
Les notes rangées :  [11 14 17 18]


In [66]:
display(revenus_array) #display plus enrichi que print et specialement concus pour jupyter

array([1800, 1900,    0,    0,    0])

Notez qu'en python vous pouvez utiliser le '_' aka 'underscore' comme séparateur de milliers. En effet, '1 000 000' est plus facile à lire que '1000000'.

Création de array multidimensionnel

In [ ]:
tab1 = np.array([[1,2],[3,4],[5,6]])
tab2 = np.array([1,2,3],[4,5,6])